#pragma once

#include <string>
#include <list>

#ifdef _WIN32		// Windows (x64 and x86)
#include <Windows.h>
#include <midlbase.h>
#include <gdiplus.h>

#pragma comment(lib, "gdiplus")
#endif

class HighlightTextPainter
{

public:
	struct ITextSplitter
	{
		virtual void Split(const wchar_t* text, const wchar_t* keywords, std::list<std::pair<size_t, bool>>& startIndice) = 0;
	};

	struct ITextPainter
	{
		virtual void MeasureText(const wchar_t* text, int len, float& cx, float& cy) = 0;
		virtual void DrawText(const wchar_t* text, int len, float x, float y, float w, float h, bool highlight, bool selected) = 0;
	};

	HighlightTextPainter(const wchar_t* text, const wchar_t* keyword, bool multiLine = true);
	HighlightTextPainter(ITextSplitter* splitter, const wchar_t* text, const wchar_t* keyword, bool multiLine = true);
	void Draw(ITextPainter* painter, float x, float y, float w, float h, bool selected);

	// Default splitter implementation
	class DefaultSplitter : public ITextSplitter
	{
	public:
		DefaultSplitter(bool caseSensitive = true) : _caseSensitive(caseSensitive) {}
	public:
		virtual void Split(const wchar_t* text, const wchar_t* keywords, std::list<std::pair<size_t, bool>>& startIndice);
	private:
		bool _caseSensitive;
	};

	// Default painter implementation
	class GDIPainter : public ITextPainter
	{
	public:
		GDIPainter(HDC hDC) : _hdc(hDC)
		{}

		virtual void MeasureText(const wchar_t* text, int len, float& cx, float& cy);
		virtual void DrawText(const wchar_t* text, int len, float x, float y, float w, float h, bool highlight, bool selected);

	protected:
		HDC _hdc;
	};

#ifdef _WIN32		// Windows (x64 and x86)
	// Default GDI Plus painter implementation
	class GDIPlusPainter : public ITextPainter
	{
	public:
		GDIPlusPainter(Gdiplus::Graphics& g, Gdiplus::Font& font, Gdiplus::StringFormat& format, BYTE alpha = 255)
			: _graphics(g)
			, _font(font)
			, _format(format)
			, _alpha(alpha)
		{}

		virtual void MeasureText(const wchar_t* text, int len, float& cx, float& cy);
		virtual void DrawText(const wchar_t* text, int len, float x, float y, float w, float h, bool highlight, bool selected);

	protected:
		Gdiplus::Graphics& _graphics;
		Gdiplus::Font& _font;
		Gdiplus::StringFormat& _format;
		BYTE _alpha;
	};
#endif

protected:
	struct TextInfo
	{
		bool highlight;
		float offsetX;
		float offsetY;
		size_t linebreak;
	};

	int GetNumCharsInLine(ITextPainter* painter, const wchar_t* text, int len, float w);
	void FindLineBreaks(ITextPainter* painter, float w, float h);
	void ApplyLineBreaks(ITextPainter* painter, float w, float h);

	bool _multiLineText;
	std::wstring _text;		// Original text
	std::list<size_t> _lineBreaks;		// Position of line-breaks
	std::list<std::pair<size_t, bool>> _seg;	// Initial segments generated by the splitter
	std::list<std::pair<size_t, TextInfo>> _dynseg;		// Run-time segments, with information for drawing
};

